### ISSUE TITLE
Development for Wexlet Tab 7t + 3G

### ISSUE THREAD

**Issue by JeanPaulLucien** [Unlegacy-Android/android_kernel_nvidia_tegra3#1]
Good afternoon.
What about development the core for Wexler Tab 7t + 3G?
About model: https://market.yandex.ru/product--planshet-wexler-tab-7t-32gb-3g/10383622
Big forum (russian) wih firmware and sources: https://4pda.ru/forum/index.php?showtopic=426283
The most similar device is Lenovo A2109.

I have this model, ready to provide assistance. Also may assist in development, but I haven't experience in this field. So, if you wish attract me, write detailed instruction.

P.S. Because I attract more people to development, allow to write here on Russian.

**Comment by clamor-s** [comment]
If you have enough building powers I can help with unofficial wexler bringup

**Comment by JeanPaulLucien** [comment]
What do you mean 'building powers'? I'm not strong in English.

I imagine this process weakly. Let's try, I'm not sure that it will be fast.  Especially if it will needed to download several GBs. What is needed to start?

Ты русский знаешь, или я ошибаюсь? :smile:

**Comment by clamor-s** [comment]
You need approx 100-120G of space on PC, >4G of RAM, fast unlimited internet and 4 core CPU (preferably from new generations). Although, you may start bring up with recovery tests.

**Comment by JeanPaulLucien** [comment]
Yeah... download 100-120 GB from internet is problem. :sad: What do I need to download? Make a list to I could complete this step, because probably I will download it all through my friend to not wait much.

**Comment by clamor-s** [comment]
You may start bring up with recovery tests. This will take a lot less resources. You may find me on telegram @Clamor_S but only if you are ready to work a lot.

**Comment by JeanPaulLucien** [comment]
I will try to contact in near time. I need to install and reg in Telegram. I hope I do it to weekend.

**Comment by byaka** [comment]
_subscribed_

**Comment by andi34** [comment]
https://www.unlegacy-android.org/projects/unlegacy-android/wiki/Sync_ua
